import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { loadRawContent } from './load';
import { validateContent } from './validate';
import { checkContent, linkContent, ContentCheckError } from './link';
import type { Content, LinkDiagnostics } from './schema';

export interface BuildOptions {
  rootDir: string;
  outFile: string;
  strict: boolean;
}

export interface BuildResult {
  content: Content;
  diagnostics: LinkDiagnostics;
}

/**
 * Load, validate and link the content graph, then write a typed TS bundle.
 * Strict mode refuses to write on any dangling reference, cycle, unreachable
 * world, or an empty content root.
 */
export async function buildContent(opts: BuildOptions): Promise<BuildResult> {
  const content = validateContent(loadRawContent(opts.rootDir));
  const diagnostics = linkContent(content);

  if (opts.strict) {
    if (Object.keys(content.worlds).length === 0) {
      throw new ContentCheckError(`content root is empty: ${opts.rootDir}`);
    }
    checkContent(content);
  }

  const body = [
    '// GENERATED by tools/build-content.ts — do not edit; edit content/ and rebuild.',
    "import type { Content, LinkDiagnostics } from '../../tools/content/schema';",
    '',
    `export const content: Content = ${JSON.stringify(content, null, 2)};`,
    '',
    `export const diagnostics: LinkDiagnostics = ${JSON.stringify(diagnostics, null, 2)};`,
    '',
  ].join('\n');

  mkdirSync(dirname(opts.outFile), { recursive: true });
  writeFileSync(opts.outFile, body);
  return { content, diagnostics };
}