import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { loadRawContent } from './load';
import { validateContent } from './validate';
import { checkContent, linkContent, ContentCheckError } from './link';
import { validateScenarios } from './scenarios';
import type { Content, ContentDiagnostics } from './schema';

export interface BuildOptions {
  rootDir: string;
  outFile: string;
  strict: boolean;
}

export interface BuildResult {
  content: Content;
  diagnostics: ContentDiagnostics;
}

/**
 * Load, validate, link, and scenario-check the content graph, then write a typed
 * TS bundle. Strict mode refuses to write on any dangling reference, cycle,
 * unreachable world, invalid scenario, or an empty content root.
 */
export async function buildContent(opts: BuildOptions): Promise<BuildResult> {
  const content = validateContent(loadRawContent(opts.rootDir));
  const diagnostics: ContentDiagnostics = {
    ...linkContent(content),
    scenarioProblems: validateScenarios(content),
  };

  if (opts.strict) {
    if (Object.keys(content.worlds).length === 0) {
      throw new ContentCheckError(`content root is empty: ${opts.rootDir}`);
    }
    checkContent(content);
    if (diagnostics.scenarioProblems.length) {
      const lines = diagnostics.scenarioProblems.map((p) => `${p.mechanic}: ${p.problem}`);
      throw new ContentCheckError(`scenario problems:\n  ${lines.join('\n  ')}`);
    }
  }

  const body = [
    '// GENERATED by tools/build-content.ts — do not edit; edit content/ and rebuild.',
    "import type { Content, ContentDiagnostics } from '../../tools/content/schema';",
    '',
    `export const content: Content = ${JSON.stringify(content, null, 2)};`,
    '',
    `export const diagnostics: ContentDiagnostics = ${JSON.stringify(diagnostics, null, 2)};`,
    '',
  ].join('\n');

  mkdirSync(dirname(opts.outFile), { recursive: true });
  writeFileSync(opts.outFile, body);
  return { content, diagnostics };
}